romSerialNumAddr = $800a

SCSI_OPCODE_TEST_UNIT_READY = $00
SCSI_OPCODE_REZERO_UNIT = $01
SCSI_OPCODE_READ = $08

OPCODE_STA = $8d
OPCODE_STX = $8e
OPCODE_STY = $8c
OPCODE_LDA = $ad
OPCODE_LDX = $ae
OPCODE_LDY = $ac
OPCODE_BIT = $2c

IO1 = $de00
IO2 = $df00

READ_BUFFER_1 = $91e0
READ_BUFFER_2 = $93e0

vBorderCol = $d020
