call build activate
call build adjindex
call build alocatcn
call build alocatrn		
call build alocexrn
call build altserch
call build apndexrn
call build appendrn
call build autoupdt
call build autocopy
call build autodel
call build automove
call build b
call build build
call build buildindex
call build catalogr
call build change
call build checksum
call build clear
call build closefil
call build cmndchn1
call build cmndchn2
call build commload
call build config
call build configlu
call build convrtio
call build copy
call build creditsb
call build d
call build dealexrn
call build dealoccn
call build dealocrn
call build del
call build di
call build diag
call build dir
call build directry
call build dosoverly
call build dump
call build era
call build errorhan
call build fastcopy
call build fastcpqd
call build fetch
call build fileprot
call build findfil2
call build go64boot_cd00
call build go64boot
call build indxmod0
call build indxmod1
call build indxmod2
call build indxmod3
call build indxmod4
call build indxmod5
call build indxmod6
call build indxmod7
call build initc064
call build l
call build ltkernal
call build lu
call build luchange
call build merge
call build messfile
call build new
call build oops
call build openrand
call build query
call build recover
call build renum
call build s
call build sb2
call build scramidn
call build setup
call build ship
call build sysboot
call build type
call build user
call build validate




