rm s1.d64
c1541 -format "sysgen 12189072a",01 d64 s1.d64
./putoutputond64.sh b
./putrelocatedond64.sh l
./putrelocatedond64.sh d
./putoutputond64.sh sb2
./putrelocatedond64.sh s
./putrelocatedond64.sh di
./putrelocatedond64.sh lu
./putrelocatedond64.sh del
./putrelocatedond64.sh dir
./putrelocatedond64.sh era
./putrelocatedond64.sh new
./putrelocatedond64.sh diag
./putoutputond64.sh setup
./putrelocatedond64.sh copy
./putrelocatedond64.sh dump
./putrelocatedond64.sh ship
./putrelocatedond64.sh user
./putrelocatedond64.sh oops
./putrelocatedond64.sh type
./putrelocatedond64.sh build
./putrelocatedond64.sh clear
./putrelocatedond64.sh fetch
./putrelocatedond64.sh merge
./putrelocatedond64.sh renum
./putrelocatedond64.sh query
./putrelocatedond64.sh change
./putrelocatedond64.sh config
./putrelocatedond64.sh idxm0128
./putrelocatedond64.sh idxm1128
./putrelocatedond64.sh idxm2128
./putrelocatedond64.sh idxm3128
./putrelocatedond64.sh autodel
./putrelocatedond64.sh idxm4128
./putrelocatedond64.sh idxm5128
./putrelocatedond64.sh idxm6128
./putrelocatedond64.sh idxm7128
./putrelocatedond64.sh close128
./putrelocatedond64.sh initc064
./putrelocatedond64.sh initc128
./putrelocatedond64.sh subcl128
./putrelocatedond64.sh openf128
./putrelocatedond64.sh recover
./putrelocatedond64.sh sysbt128
./putrelocatedond64.sh fastfd81
./putrelocatedond64.sh cmndchn1
./putrelocatedond64.sh cmndchn2
./putrelocatedond64.sh dosov128
./putrelocatedond64.sh findfil2
./putrelocatedond64.sh ltkrn128
./putrelocatedond64.sh fastcp1a
./putrelocatedond64.sh fastcp2a
./putrelocatedond64.sh dealoccn
./putrelocatedond64.sh go64boot
./putrelocatedond64.sh loadrnd2
./putrelocatedond64.sh loadrnd3
./putrelocatedond64.sh fastcpy1
./putrelocatedond64.sh fastcpy2
./putrelocatedond64.sh fastcpdd
./putrelocatedond64.sh adjindex
./putrelocatedond64.sh alocatcn
./putrelocatedond64.sh catalogr
./putrelocatedond64.sh creditsb
./putrelocatedond64.sh dealocrn
./putrelocatedond64.sh commload
./putrelocatedond64.sh findfile
./putrelocatedond64.sh gocpmode
./putrelocatedond64.sh indxmod0
./putrelocatedond64.sh activate
./putrelocatedond64.sh alocatrn
./putrelocatedond64.sh alocexrn
./putrelocatedond64.sh altserch
./putrelocatedond64.sh appendrn
./putrelocatedond64.sh checksum
./putrelocatedond64.sh closefil
./putrelocatedond64.sh configlu
./putrelocatedond64.sh dealexrn
./putrelocatedond64.sh expnrand
./putrelocatedond64.sh fastcprm
./putrelocatedond64.sh subcallr
./putrelocatedond64.sh indxmod1
./putrelocatedond64.sh indxmod2
./putrelocatedond64.sh fastfdos
./putrelocatedond64.sh fastcopy
./putrelocatedond64.sh automove
./putrelocatedond64.sh directry
./putrelocatedond64.sh errorhan
./putrelocatedond64.sh fastcpqd
./putrelocatedond64.sh fileprot
./putrelocatedond64.sh indxmod3
./putrelocatedond64.sh indxmod4
./putrelocatedond64.sh indxmod5
./putrelocatedond64.sh indxmod6
./putrelocatedond64.sh indxmod7
./putrelocatedond64.sh loadcntg
./putrelocatedond64.sh loadrand
./putrelocatedond64.sh ltkernal
./putrelocatedond64.sh luchange
./putrelocatedond64.sh autocopy
./putrelocatedond64.sh autoupdt
./putrelocatedond64.sh convrtio
./putrelocatedond64.sh openfile
./putrelocatedond64.sh openrand
./putrelocatedond64.sh sysbootr
./putrelocatedond64.sh buildindex
./putrelocatedond64.sh dosovrly
./putrelocatedond64.sh openrela
./putrelocatedond64.sh relaexpn
./putrelocatedond64.sh savetodv
./putrelocatedond64.sh scramidn
./putrelocatedond64.sh validate
./putrelocatedond64.sh messfile



