./build.sh activate
./build.sh adjindex
./build.sh alocatcn
./build.sh alocatrn		
./build.sh alocexrn
./build.sh altserch
./build.sh apndexrn
./build.sh appendrn
./build.sh autoupdt
./build.sh autocopy
./build.sh autodel
./build.sh automove
./build.sh b
./build.sh build
./build.sh buildindex
./build.sh catalogr
./build.sh change
./build.sh checksum
./build.sh clear
./build.sh closefil
./build.sh cmndchn1
./build.sh cmndchn2
./build.sh commload
./build.sh config
./build.sh configlu
./build.sh convrtio
./build.sh copy
./build.sh creditsb
./build.sh d
./build.sh dealexrn
./build.sh dealoccn
./build.sh dealocrn
./build.sh del
./build.sh di
./build.sh diag
./build.sh dir
./build.sh directry
./build.sh dosoverly
./build.sh dump
./build.sh era
./build.sh errorhan
./build.sh fastcopy
./build.sh fastcpqd
./build.sh fetch
./build.sh fileprot
./build.sh findfil2
./build.sh go64boot_cd00
./build.sh go64boot
./build.sh indxmod0
./build.sh indxmod1
./build.sh indxmod2
./build.sh indxmod3
./build.sh indxmod4
./build.sh indxmod5
./build.sh indxmod6
./build.sh indxmod7
./build.sh initc064
./build.sh l
./build.sh ltkernal
./build.sh lu
./build.sh luchange
./build.sh merge
./build.sh messfile
./build.sh new
./build.sh oops
./build.sh openrand
./build.sh query
./build.sh recover
./build.sh renum
./build.sh s
./build.sh sb2
./build.sh scramidn
./build.sh setup
./build.sh ship
./build.sh sysboot
./build.sh type
./build.sh user
./build.sh validate




