call build activate
call build adjindex
call build autocopy
call build autodel
call build b
call build build
call build buildindex
call build catalogr
call build creditsb
call build checksum
call build config
call build configlu
call build convrtio
call build d
call build di
call build diag
call build dir
call build dosoverly
call build dump
call build era
call build errorhan
call build fastcopy
call build fastcpqd
call build fetch
call build fileprot
call build findfil2
call build go64boot_cd00
call build go64boot
call build initc064
call build l
call build ltkernal
call build lu
call build luchange
call build merge
call build messfile
call build new
call build oops
call build openrand
call build query
call build recover
call build renum
call build s
call build sb2
call build scramidn
call build setup
call build ship
call build sysboot
call build type
call build user
call build validate




