call test_file activate activate.r
call test_file adjindex adjindex.r
call test_file autocopy autocopy.r
call test_file autodel autodel.r
call test_file automove automove.r
call test_file b b
call test_file build build.r
call test_file buildindex buildindex.r
call test_file catalogr catalogr.r
call test_file change change.r
call test_file checksum checksum.r
call test_file clear clear.r
call test_file config config.r
call test_file configlu configlu.r
call test_file convrtio convrtio.r
call test_file copy copy.r
call test_file creditsb creditsb.r
call test_file d d.r
call test_file del del.r
call test_file di di.r
call test_file diag diag.r
call test_file dir dir.r
call test_file dosoverly dosovrly.r
call test_file dump dump.r
call test_file era era.r
call test_file errorhan errorhan.r
call test_file fastcopy fastcopy.r
call test_file fastcpqd fastcpqd.r
call test_file fetch fetch.r
call test_file fileprot fileprot.r
call test_file findfil2 findfil2.r
call test_file go64boot go64boot.r
call test_file indxmod0 indxmod0.r
call test_file indxmod1 indxmod1.r
call test_file indxmod2 indxmod2.r
call test_file indxmod3 indxmod3.r
call test_file indxmod4 indxmod4.r
call test_file indxmod5 indxmod5.r
call test_file indxmod6 indxmod6.r
call test_file indxmod7 indxmod7.r
call test_file initc064 initc064.r
call test_file l l.r
call test_file ltkernal ltkernal.r
call test_file lu lu.r
call test_file luchange luchange.r
call test_file merge merge.r
call test_file messfile messfile.r
call test_file new new.r
call test_file oops oops.r
call test_file openrand openrand.r
call test_file query query.r
call test_file recover recover.r
call test_file renum renum.r
call test_file s s.r
call test_file sb2 sb2
call test_file scramidn scramidn.r
call test_file setup setup
call test_file ship ship.r
call test_file sysboot sysbootr.r
call test_file type type.r
call test_file user user.r
call test_file validate validate.r

